### ISSUE TITLE
Twig Fatal Error due to missing variable

### ISSUE THREAD

**Issue by michaelcullum** [opencfp/opencfp#262]
A fatal error now occurs on /admin/review

```
[16-Nov-2015 02:30:18 Europe/Paris] PHP Fatal error:  Uncaught exception 'Twig_Error_Runtime' with message 'Variable "current_page" does not exist in "layouts/default.twig" at line 12' in \var\www\opencfp\vendor\twig\twig\lib\Twig\Template.php:391
```

**Comment by jakefolio** [comment]
I believe this PR should fix it: https://github.com/opencfp/opencfp/pull/263

**Comment by michaelcullum** [comment]
@jakefolio Just pulled your fix and I'm still getting the exception.

**Comment by jakefolio** [comment]
@michaelcullum really? I just branched off master, made the changes, and spun up local php test server. The URL you specified is working fine for me.'

Have you ran all the migrations?

**Comment by chartjes** [comment]
Just tried with a fresh install, does not generate any errors. Closing as resolved

**Comment by vlucas** [comment]
Heads up: I ran into this, but it was when I was using the built-in PHP server via:
```
php -S localhost:8080 web/index.php
```

The pages all work, but none of the static assets load - for some reason you get the "Variable "current_page" does not exist" errors instead. You probably just need to be clear in the docs that the PHP dev server is not supported (or fix the asset loading! :)).

**Comment by chartjes** [comment]
It does state in the README that Apache 2+ with mod_rewrite enabled is a requirement. Anything else isn't supported.

**Comment by vlucas** [comment]
Yeah - I saw the Apache/Nginx - I just didn't want to have to set those up on my local machine to make a few styling changes, so I tried the built-in PHP webserver first. Not a big issue, but that's what I imagine this guy did as well.

**Comment by jakefolio** [comment]
@vlucas I think I've always used Homestead for developing with OpenCFP. If we setup a basic router script for the built-in PHP server, that should resolve the issues, no?

**Comment by chartjes** [comment]
Yes, that would be great.
